### ISSUE TITLE
Roadmap: Improve hassio frontend

### ISSUE THREAD

**Issue by c727** [home-assistant/hassio#301]
1. UI improvements
- [ ] Addon section
- [ ] Snapshot section
- [ ] Advanced section
- [ ] Hide some options behind a developer toggle (like local addons and network stuff)
2. HA integration
- [ ] optimize HA functions, like restart, for hassio
- [ ] add `hassio:` to HA config by default
3. Odds and ends to improve the usability
- [ ] Several language improvements (by a native speaker)
- [ ] rename "Google Assistant" addon to something with "SDK" in name to avoid confusion with the HA component
- [ ] fix inconsistencies like "snapshots" are named "backups" in samba addon
- [ ] improve logoutput of config check addon
- [ ] maybe install some essentially addons like samba and SSH by default

Here is a first concept for the addon section
![hassio](https://user-images.githubusercontent.com/11984118/34698545-efc2853e-f4d8-11e7-958e-d712ee9d9c39.png)

**Comment by pvizeli** [comment]
There are some points they will be hard:

- We have a own API check the config for the running version. We should implement this to UI. The config check add-on is more like a utility to check the config for next release but should not be used to check the config with running version.
- Snapshot/Backup. At view now, its not nice, yes. But that is not easy changeable, since it break any add-on they work with it. For statement now, I would like to rename `/config` to `/homeassistant` while it can be misunderstood `config`. I had copy this from official docker image but over the time, it was a bad idea. We can try to plane a big breaking change and hope all add-on developer will help on this movement but we don't make he happy with this...

**Comment by ciotlosm** [comment]
I also vote to drop:
![screen shot 2018-01-09 at 21 35 12](https://user-images.githubusercontent.com/7738048/34739468-09d0e054-f585-11e7-98ef-9201e7d9cd0e.png)

Restart is already in many places (configuration menu, container, hassio CLI) that this makes no sense. Also this doesn't work on mobile.

**Comment by pvizeli** [comment]
It's not the same restart as on other places

**Comment by frenck** [comment]
We could "fix" the restart on other places, by detecting the presence of the HASSIO env variable on those buttons and present or trigger a different logic, right?

**Comment by c727** [comment]
Can we have an API to delete snapshots?
Can the supervisor detect if a snapshot got deleted (without restarting it)?

**Comment by cogneato** [comment]
It would be good to have the "visit website" link that is visible before installing an addon persist to the installed addon itself so the setup instructions (when present) are more easily accessed.

**Comment by pvizeli** [comment]
@c727 I can make a remove function.

You need not reload the supervisor. You can touch on reload on snapshot page. It run also a job in background they will update the snapshots if someone remove this from folder.

**Comment by ciotlosm** [comment]
@pvizeli can "updater:" be fixed to show update for hassio if you're running hassio? Would make more sense I think, just like restart.

**Comment by pvizeli** [comment]
Like this? https://github.com/home-assistant/home-assistant/pull/11571

**Comment by c727** [comment]
ciotlosm and I started to update the frontend. is there something you like to see changed or miss? (advanced is still the same)

![new_addons](https://user-images.githubusercontent.com/11984118/35182506-c1eaad9c-fdd6-11e7-9a01-74671b0b94ba.png)
![new_dashboard](https://user-images.githubusercontent.com/11984118/35182507-c1ffbade-fdd6-11e7-93a6-c778d151353c.png)
![new_snapshots](https://user-images.githubusercontent.com/11984118/35182508-c2152946-fdd6-11e7-9889-984725ed02c9.png)
![new_snapshots2](https://user-images.githubusercontent.com/11984118/35182509-c22a74d6-fdd6-11e7-8d6f-15ddbbd8f881.png)
![new_store](https://user-images.githubusercontent.com/11984118/35182510-c23f22f0-fdd6-11e7-8a54-8891cb06a056.png)

**Comment by pvizeli** [comment]
Amazing

**Comment by frenck** [comment]
Looks great guys! That is a major leap forward 🚀 

On the dashboard, it shows the currently installed add-ons. Personally, I would like to see which one is running and which isn't. On an ecstatic side note, maybe add the add-on icons as well?

**Comment by ciotlosm** [comment]
@frenck there are currently just logos which don't have fixed ratio and usually are petty big. If icons would be provided by addons that would be great to add. 

The running/ stopped is shown by the "puzzle" icon being green or grey. The same icon transforms to an orange arrow up when an update is available for an installed addon.

**Comment by pvizeli** [comment]
I will see a PR :)

**Comment by c727** [comment]
Our problem is the new iframe panel... Frontend dev does not seem to work atm:

`element-mixin.html:593 GET http://hassio:8123/home-assistant-polymer/hassio/index.html 404 (Not Found)`

**Comment by pvizeli** [comment]
@c727 on this point, I can't help -> @balloob ?

**Comment by c727** [comment]
balloob fixed it already :)

**Comment by pvizeli** [comment]
I think the long_description should be displayed on add-on store page but not on the add-on "config panel".

**Comment by c727** [comment]
**Hass.io API**
1. Isn't it inconvenient that we have to use 3 APIs for the add-ons:
- `supervisor/info` for installed add-on **with running-status** <- dashboard
- `addons` for all add-ons in all repos <- add-on store
- `addons/53caca22_mopidy-cast/info` for add-on details <- add-on details

2. same for snapshots, `snapshots` has some information of `snapshots/6dbde1f3/info`, but not all

3. generic information for HA, Host, Supervisor also have separate APIs...

so can we merge them all into API (like the hass-object) or combine some of them?

**Comment by balloob** [comment]
If you combine them all into 1 object, you need to load them all before being able to show any page. There is no need to always load all the available add-ons. That info is only needed in the add-on store.
