### ISSUE TITLE
Roadmap: Improve Snips Addon for HassIO

### ISSUE THREAD

**Issue by tschmidty69** [home-assistant/hassio#322]
Placeholder to comment on improvements to snips add on for hassio

- [ ] Default Intents (turnOn, turnOff, addToShoppingList)
- [ ] Default assistant - will have snips include one configured for Hassio
- [ ] Use Hass MQTT by default, currently bridges all topics which is inefficient since Snips sends all audio frames over MQTT

**Comment by balloob** [comment]
Home Assistant has a TurnOn and TurnOff intent available, but they currently live inside the `conversation` component ([source](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/conversation.py#L165-L224)). Would be easy to move them up to be part of the `homeassistant.components.async_setup`.

**Comment by tschmidty69** [comment]
Hmm, not sure the best place. Snips should depend on the conversation component I think at least for hassio. Since the idea for the snips addon would be that we would control the intents for a smart home setup I think it's ok to keep it there and extend it with any other default type intents. Moving it could potentially conflict with other intents users might want to configure that aren't using hassio. I think for now we can make it work ok. For example I already have a snips sending an intent to add to the shopping list that I simply have handled by the conversation component, so I think we can follow that model.

**Comment by balloob** [comment]
All Home Assistant built-in intents should always be prefixed with `Hass`. So they should never conflict.

We should not depend on the conversation component to register intents. The conversation component is offering an API to offer conversations from the frontend. It is not the "intent" component.

**Comment by tschmidty69** [comment]
True, but as it is we register HassTurnOn and HassTurnOff as part of conversation component, and HassShoppingListAddItem and HassShoppingListLastItems as part of the shopping list component. I think they should be moved out of those "somewhere" as part of something more extensible. 

I think you are thinking specific to the snips component though?

I was thinking maybe a platform called hass_intents that registers those Hass* intents and handlers. Would give us one place to manage this. Shopping list could just be what it is, a platform and api for managing a shopping list, conversation can just be a component to parse speech and fire intents.

**Comment by balloob** [comment]
Components should register the intents that are related to their component. That is the only way we can also know that the component has loaded.

The file `components/__init__.py` already registers `homeassistant.turn_on` and `homeassistant.turn_off` services. It is the spot to register the `HassTurnOn` and `HassTurnOff` intents.

**Comment by tschmidty69** [comment]
Had a longer response, but let's just say: Set HassTurnOn and HassTurnOff in __init__, moved from conversation. 

Other components can register their own intents and handlers as they wanted, as in someone could add turnLightsOn to lights or notifyIntent to the other platforms but for now just implement the basic turn entity off/on.

**Comment by pvizeli** [comment]
I think we need a API how can a add-on read the home-assistant config and discovery/trigger components on home-assistant over the supervisor.

**Comment by tschmidty69** [comment]
@pvizeli can we update the hassio-addon-snips docker image? If you want to give me access to push to docker I can do it (tschmidty)

One other thing I'd like to do is provide a default hassio assistant which could still be overwritten by the user. It's only about 25MB so I would think it would be fine to include in the image itself. I think that is a huge hurdle for people and hassio should be about reducing those.

**Comment by pvizeli** [comment]
@tschmidty69 you can make a PR to add-on repository.

We support custom image. So feel free to use your own image and refresh itself.
